name: 'Release'

on:
  workflow_dispatch:
jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install bun
        run: |
          curl https://bun.sh/install | bash

      - name: Add bun to Path
        run: echo "/home/runner/.bun/bin" >> $GITHUB_PATH;

      - name: Set Github Actions bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Get version & asign
        id: get_version
        run: |
          cd packages/patch-package
          variable=$(jq --raw-output '.version' package.json)
          echo ::set-output name=version::$variable
      - name: Publish a NPM package
        run: |
          /home/runner/.bun/bin/bun install
          cd packages/patch-package
          /home/runner/.bun/bin/bun install
          cd ../..
          /home/runner/.bun/bin/bun run build
          cd packages/patch-package
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish releases
        run: |
          /home/runner/.bun/bin/bun install
          node ./scripts/create-release.mjs ${{ github.event.inputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}